{% set name = "des-pizza-cutter-masking" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/beckermr/pizza-cutter-masking/archive/refs/tags/{{ version }}.tar.gz
  sha256: 41696e4e376874ae2dd2ad58968f7412313a983cbc05f26782af2451e7762e6e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  # this recipe is not noarch because it uses the setuptools scripts functionality
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - healsparse
    - fitsio
    - tqdm
    - esutil
    - hpgeom

test:
  imports:
    - pizza_cutter_masking

about:
  home: https://github.com/beckermr/pizza-cutter-masking
  summary: 'mask making codes for pizza-cutter'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
